// Generated by Selenium IDE
package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import java.time.Duration;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.micrometer.core.annotation.TimedSet;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  // @Test
  // public void dEFECT1FUNFEED() {
  //   driver.get("http://localhost:8080");
  //   driver.findElement(By.linkText("Feed-A-Cat")).click();
  //   driver.findElement(By.cssSelector(".btn")).click();
  //   assertThat(driver.findElement(By.id("feedResult")).getText(), is("Cat fight!"));
  //   driver.close();
  // }
  // @Test
  // public void dEFECT2FUNGREETACAT() {
  //   driver.get("http://localhost:8080");
  //   driver.findElement(By.linkText("Rent-A-Cat")).click();
  //   driver.findElement(By.id("rentID")).click();
  //   driver.findElement(By.id("rentID")).sendKeys("1");
  //   driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
  //   driver.findElement(By.linkText("Greet-A-Cat")).click();
  //   assertThat(driver.findElement(By.cssSelector("#greeting > h4")).getText(), is("Meow!Meow!"));
  //   driver.close();
  // }
  // @Test
  // public void dEFECT3FUNGREETACATWITHNAME() {
  //   driver.get("http://localhost:8080");
  //   driver.findElement(By.linkText("Rent-A-Cat")).click();
  //   driver.findElement(By.id("rentID")).click();
  //   driver.findElement(By.id("rentID")).sendKeys("1");
  //   driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
  //   driver.get("http://localhost:8080greet-a-cat/Jennyanydots");
  //   {
  //     List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Jennyanydots is not here.\')]"));
  //     assert(elements.size() > 0);
  //   }
  //   driver.close();
  // }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    {
      WebElement element = driver.findElement(By.xpath("//li[8]/a"));
      String attribute = element.getAttribute("href");
      vars.put("href", attribute);
    }
    assertEquals(vars.get("href").toString(), "http://localhost:8080/reset");
    driver.close();
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.linkText("Reset")).click();
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(1)")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(2)")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText(), is("ID 3. Mistoffelees"));
    driver.close();
  }
  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    {
      WebElement element = driver.findElement(By.xpath("//li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("title", attribute);
    }
    assertEquals(vars.get("title").toString(), "http://localhost:8080/images/cat2.jpg");
    driver.close();
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[3]/img"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[4]/img"));
      assert(elements.size() == 0);
    }
    assertThat(driver.findElement(By.xpath("//div/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    driver.close();
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Rent\')]"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Return\')]"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("rentID")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.xpath("//button")).click();
    assertThat(driver.findElement(By.xpath("//div/ul/li")).getText(), is("Rented out"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(2)")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText(), is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.id("rentResult")).getText(), is("Success!"));
    driver.close();
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.xpath("//div[3]/div[3]/button")).click();
    assertThat(driver.findElement(By.xpath("//div/ul/li")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//div/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//div/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    driver.close();
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Feed\')]"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080");
    driver.manage().window().setSize(new Dimension(900, 718));
    driver.findElement(By.xpath("//li[4]/a")).click();
    driver.findElement(By.xpath("//input")).click();
    driver.findElement(By.xpath("//input")).sendKeys("6");
    driver.findElement(By.xpath("//button")).click();
    assertThat(driver.findElement(By.xpath("//div[4]")).getText(), is("Nom, nom, nom."));
    driver.close();
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow!Meow!Meow!\')]"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//h4[contains(.,\'Meow! from Jennyanydots.\')]"));
      assert(elements.size() > 0);
    }
    driver.close();
  }
}
